### ISSUE TITLE
Feature request:  table with muck action

### ISSUE THREAD

**Issue by NitroLine** [kuco23/pokerlib#11]
Hi, i want to add some new table implementation. The main feature is muck action to users.
 
In end of round, when there are several players left, the player who had the last word at the table opens first, and the rest in the order of distribution, clockwise.
The first player to open shows the cards by default, and the rest should have an option after him - show the cards or muck (hide the cards and discard), if they have a losing combination in relation to the already opened one.
If they have a combination stronger - there is no option to muck, in this case they are opened by default.

**Comment by kuco23** [comment]
Implemented showing and mucking inside the original Round/Table, where [here](https://github.com/kuco23/pokerlib/blob/master/pokerlib/_round.py#L267) `_showdown` can be customized. I haven't found any clear ruling on what the official showdown is, so thought it might be good to be able to customize it.  Also, the choice for premature winner to show cards is now inside Round, so `TableWithChoiceToShowCards` doesn't need exist anymore. 

Will keep the issue open for a while so I can test a bit.
