### ISSUE TITLE
Feature request: choose player place in table

### ISSUE THREAD

**Issue by NitroLine** [kuco23/pokerlib#2]
Hello, I want to implement the choice of the place where the incoming player will sit. 
Therefore, it is necessary that when adding a player, the place index is transmitted. And PLAYERJOIND action will return this index.

 I will now make a fork where I will try to implement it. 
 Any tips on how to make this easier?

**Comment by kuco23** [comment]
Hi, this feature would be very welcome. I think there's some work to do here though. I have player groups implemented as lists of players, but it makes more sense for them to be implemented as a seat arrangement, so if you have a table with 9 seats, the player group should be a list of length 9 with some `None`s in between. With that, adding players and fetching their indices would simplify and could be added easily. But there is a lot of work to be done on [this](https://github.com/kuco23/pokerlib/blob/master/pokerlib/_player.py#L48) class (also with the naming).

**Comment by NitroLine** [comment]
#5 add new playerSeats class instead of changing PlayerGroup class

**Comment by kuco23** [comment]
Have written the tests [here](https://github.com/kuco23/pokerlib/blob/master/tests/table_test.py).
