### ISSUE TITLE
Bug: trying to run the example in readme and getting importerror

### ISSUE THREAD

**Issue by weteamsteve** [kuco23/pokerlib#21]
Getting error
`ImportError: cannot import name 'Rank' from 'pokerlib.enums' (C:\Users\veter\miniconda3\lib\site-packages\pokerlib\enums.py)` while trying to run the code in readme. Tried pip installing pokerlib, tried it in a virtual environment, a whole bunch of other stuff. Also fixed the typo on the second 'pokerib'

**Comment by kuco23** [comment]
Can you run `pip show pokerlib` and verify it is `2.2.6`?
