### ISSUE TITLE
Feature request: return dealer id

### ISSUE THREAD

**Issue by NitroLine** [kuco23/pokerlib#8]
Hi, i want to show users, who dealer now. I add this field in my table class using this code.
```
        if out_id.name == enums.RoundPublicOutId.SMALLBLIND.name:
            kwargs['dealer_id'] = self.players[self.round.current_index].id
```
But it might be nice if you add it by default

**Comment by kuco23** [comment]
You can call `table.round.players[table.round.button]`. Button is the `dealer`'s index.
